[package]
name = "wormhole-charter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0"
quote = "1.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"